name: Auto Merge Release to Main

on:
  push:
    branches:
      - release/*

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Merge Release to Main
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git fetch origin main
        git checkout main
        git merge --no-ff "${GITHUB_REF/refs\/heads\/release\//}"
        git push origin main

      env:
        PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  